import { test, expect } from '@playwright/test';

test('Login Test automatically generated by playwright code generator chrome browser', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('manda user').click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});