const {test, expect} = require("@playwright/test")
test.use({headless:false})
test("Handle Alert", async function({page})
{
    await page.goto("https://the-internet.herokuapp.com/javascript_alerts")
    page.on("dialog", async function(dialog)
    {   expect(dialog.type()).toContain("alert")
        expect(dialog.message()).toContain("I am a JS Alert")
        await dialog.accept()
    })
    await page.locator("//button[normalize-space()='Click for JS Alert']").click()
    await page.waitForTimeout(3000)
})
test("Handle Confirm Box", async function({page})
{
    await page.goto("https://the-internet.herokuapp.com/javascript_alerts")
    page.on("dialog", async function(dialog)
    {   expect(dialog.type()).toContain("confirm")
        expect(dialog.message()).toContain("I am a JS Confirm")
        await dialog.dismiss()
    })
    await page.locator("//button[normalize-space()='Click for JS Confirm']").click()
    await page.waitForTimeout(3000)
})
test("Handle Prompt Box", async function({page})
{
    await page.goto("https://the-internet.herokuapp.com/javascript_alerts")
    page.on("dialog", async function(dialog)
    {   expect(dialog.type()).toContain("prompt")
        expect(dialog.message()).toContain("I am a JS prompt")
        await dialog.accept("Bala")
    })
    await page.locator("//button[normalize-space()='Click for JS Prompt']").click()
    await page.waitForTimeout(3000)
})